[package]
name = "famiasm"
version = "0.1.0"
authors = ["turuturu <t.tsurumi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.x"
strum = "0.20"
strum_macros = "0.20"